### ISSUE TITLE
Authorizer

### ISSUE THREAD

**Issue by Can-Sahin** [dhsass/TCServerlessApp#1]
I am not using aws sam templates so I cant really read the template in details. Serverless framework is extremely handy in these simple cases. I would suggest you using that. But looking at your template I dont see any cognito authorizers anywhere?? Only security definition I see is signV4. There should something like this I suppose 

yml example: 

```
 securityDefinitions:
              cognitoUserPool:
                type: apiKey,
                name: "Authorization"
                in: header
                x-amazon-apigateway-authtype: cognito_user_pools
                x-amazon-apigateway-authorizer:
                  type: cognito_user_pools
                  providerARNs:
                    - arn:aws:cognito-idp:${AWS::Region}:{AWS::AccountId}:userpool/<user_pool_id>
```
